FROM php:apache AS builder

WORKDIR /var/www/html
EXPOSE 8080

RUN apt update
RUN apt install -y git

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

COPY index.php index.php

COPY composer.json composer.json

RUN composer install

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN echo "Listen 8080" >> /etc/apache2/apache2.conf

CMD ["apache2-foreground"]